name: main

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

env:
  BEPINEX_URL: https://thunderstore.io/package/download/denikson/BepInExPack_Valheim/5.4.2202/
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4.2.2

      - name: setup buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: login
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: metadata
        id: metadata
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=develop,enable=${{ github.ref == 'refs/heads/develop' }}

      - name: wget and unzip
        run: |
          wget -O BepInEx.zip "${{ env.BEPINEX_URL }}"
          unzip BepInEx.zip -d BepInEx

      - name: build and push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
